# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

# This template will build and test your projects
# * Caches downloaded dependencies and plugins between invocation.
# * Verify but don't deploy merge requests.
# * Deploy built artifacts from master branch only.

variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  #-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

  # As of Maven 3.3.0 instead of this you MAY define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # As of Maven 3.6.1, the use of `--no-tranfer-progress` (or `-ntp`) suppresses download and upload messages. The use
  # of the `Slf4jMavenTransferListener` is no longer necessary.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
#  MAVEN_CLI_OPTS: >-
#    --batch-mode
#    --errors
#    --fail-at-end
#    --show-version
#    --no-transfer-progress
#    -DinstallAtEnd=true
#    -DdeployAtEnd=true

# This template uses the latest Maven 3 release, e.g., 3.8.6, and OpenJDK 8 (LTS)
# for verifying and deploying images
# Maven 3.8.x REQUIRES HTTPS repositories.
# See https://maven.apache.org/docs/3.8.1/release-notes.html#how-to-fix-when-i-get-a-http-repository-blocked for more.
#image: maven:3-openjdk-8
image:
  name: maven:3.8.1-openjdk-17-slim-lsof
  pull_policy: if-not-present

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
# Be aware that `mvn deploy` will install the built jar into this repository. If you notice your cache size
# increasing, consider adding `-Dmaven.install.skip=true` to `MAVEN_OPTS` or in `.mvn/maven.config`
#cache:
#  paths:
#    - .m2/repository

stages:
  - .pre
  - test

unit-test:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean install -Dtest.port.closed=true -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/

session-builder-coverage-check:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'chmod +x check_session_builder.sh'
    - './check_session_builder.sh'
    - 'mvn clean install -DskipTests -am -s $MAVEN_SETTINGS_XML'
    - 'mvn test -pl timecho-session -Dtest=BuilderCoverageTest -q -s $MAVEN_SETTINGS_XML'
    - 'mvn test -pl timecho-session -Dtest=BuilderTest,SessionPoolBuilderTest -q -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
  needs: []  # 不依赖其他job，可以并行运行

integration-test-1c1d:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=8 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: 1c1d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day


integration-test-1c3d:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PClusterIT -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: 1c3d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day
table-integration-test-1c1d:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=8 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PTableSimpleIT -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: 1c1d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day


table-integration-test-1c3d:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=6 -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -pl integration-test -am -PTableClusterIT -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: 1c3d-log
    paths:
      - integration-test/target/cluster-logs
    expire_in: 7 day

ainode-test-1c1d1a:
  stage: test
  image: timechodb:AICluster
  tags:
    - gpu
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn verify -P with-integration-tests,with-ainode -DskipUTs -DConfigNodeMaxHeapSize=1024 -DDataNodeMaxHeapSize=1024 -DaiNodeMaxHeapSize=1024 -pl integration-test,iotdb-core/ainode -am -PAIClusterIT -s $MAVEN_SETTINGS_XML'
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: ainode-log
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/ainode-logs
    expire_in: 7 day

single:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT1 -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/

  artifacts:
    when: on_failure
    name: pipe-log-single
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dual-tree-auto-basic:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeAutoBasic -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-auto-basic
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dual-tree-auto-enhanced:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeAutoEnhanced -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-auto-enhanced
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dual-tree-manual:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTreeManual -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/

  artifacts:
    when: on_failure
    name: pipe-log-dual-tree-manual
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dual-table-manual-basic:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTableManualBasic -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/

  artifacts:
    when: on_failure
    name: pipe-log-dual-table-manual-basic
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

dual-table-manual-enhanced:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2DualTableManualEnhanced -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/

  artifacts:
    when: on_failure
    name: pipe-log-dual-table-manual-enhanced
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day

subscription:
  stage: test
  tags:
    - timechodb
  before_script:
    - 'mv /root/.m2/repository/org/apache/iotdb/tools /root/.m2/repository/ || true'
    - 'rm -rf /root/.m2/repository/org/apache/iotdb || true'
    - 'mv /root/.m2/repository/tools /root/.m2/repository/org/apache/iotdb/ || true'
    - 'rm -rf /root/.m2/repository/com/timecho/iotdb || true'
    - 'rm -rf /root/.m2/repository/org/apache/tsfile || true'
    - 'rm -rf /root/.m2/repository/org/apache/ratis || true'
  script:
    - 'mvn clean verify -P with-integration-tests -DskipUTs -DintegrationTest.forkCount=1 -DConfigNodeMaxHeapSize=256 -DDataNodeMaxHeapSize=768 -DClusterConfigurations=$CLUSTER1,$CLUSTER2 -pl integration-test -am -PMultiClusterIT2SubscriptionTreeArchVerification -s $MAVEN_SETTINGS_XML'
  parallel:
    matrix:
      - CLUSTER1: [HighPerformanceMode]
        CLUSTER2: [HighPerformanceMode]
  interruptible: true
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rel/ || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^rc/
    
  artifacts:
    when: on_failure
    name: pipe-log-subscription
    paths:
      - integration-test/target/cluster-logs
      - integration-test/target/pipeIT-logs
    expire_in: 7 day
